# Generated by Django 5.0.6 on 2024-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume_headline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
